spring:
  datasource:
    url: "jdbc:mysql://localhost:3309/shopee"
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    user:
      name: admin
      password: admin@123

  app:
    jwtSecret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    jwtExpirationMs: 300000
    jwtCookeieName: shopee_clone_app

#spring:
#  h2:
#    console:
#     enabled: true
#  datasource:
#    url: "jdbc:h2:mem:testdb"
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver

project:
  image: "images/"



